# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 2
    gaps_out = 2
    border_size = 1
    # Use master layout instead of dwindle
    # layout = master
    # col.active_border =  rgba(161,32,99,1) rgba(83,113,189,1) 45deg)
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 4
    inactive_opacity = .9
    # active_opacity = 1
    # dim_strength = 1.0
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
